// Generated by gencpp from file uav_mavros_simulation/goto_arucoResponse.msg
// DO NOT EDIT!


#ifndef UAV_MAVROS_SIMULATION_MESSAGE_GOTO_ARUCORESPONSE_H
#define UAV_MAVROS_SIMULATION_MESSAGE_GOTO_ARUCORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_mavros_simulation
{
template <class ContainerAllocator>
struct goto_arucoResponse_
{
  typedef goto_arucoResponse_<ContainerAllocator> Type;

  goto_arucoResponse_()
    : dist(0.0)  {
    }
  goto_arucoResponse_(const ContainerAllocator& _alloc)
    : dist(0.0)  {
  (void)_alloc;
    }



   typedef double _dist_type;
  _dist_type dist;





  typedef boost::shared_ptr< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct goto_arucoResponse_

typedef ::uav_mavros_simulation::goto_arucoResponse_<std::allocator<void> > goto_arucoResponse;

typedef boost::shared_ptr< ::uav_mavros_simulation::goto_arucoResponse > goto_arucoResponsePtr;
typedef boost::shared_ptr< ::uav_mavros_simulation::goto_arucoResponse const> goto_arucoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator1> & lhs, const ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.dist == rhs.dist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator1> & lhs, const ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_mavros_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f4fece6412db25720b2bab9f80b3473";
  }

  static const char* value(const ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f4fece6412db257ULL;
  static const uint64_t static_value2 = 0x20b2bab9f80b3473ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_mavros_simulation/goto_arucoResponse";
  }

  static const char* value(const ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 dist\n"
;
  }

  static const char* value(const ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goto_arucoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_mavros_simulation::goto_arucoResponse_<ContainerAllocator>& v)
  {
    s << indent << "dist: ";
    Printer<double>::stream(s, indent + "  ", v.dist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MAVROS_SIMULATION_MESSAGE_GOTO_ARUCORESPONSE_H
