// Generated by gencpp from file uav_mavros_simulation/target_local_pos.msg
// DO NOT EDIT!


#ifndef UAV_MAVROS_SIMULATION_MESSAGE_TARGET_LOCAL_POS_H
#define UAV_MAVROS_SIMULATION_MESSAGE_TARGET_LOCAL_POS_H

#include <ros/service_traits.h>


#include <uav_mavros_simulation/target_local_posRequest.h>
#include <uav_mavros_simulation/target_local_posResponse.h>


namespace uav_mavros_simulation
{

struct target_local_pos
{

typedef target_local_posRequest Request;
typedef target_local_posResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct target_local_pos
} // namespace uav_mavros_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_mavros_simulation::target_local_pos > {
  static const char* value()
  {
    return "fb2d2cec436c25bb2c92caf8218fe6ff";
  }

  static const char* value(const ::uav_mavros_simulation::target_local_pos&) { return value(); }
};

template<>
struct DataType< ::uav_mavros_simulation::target_local_pos > {
  static const char* value()
  {
    return "uav_mavros_simulation/target_local_pos";
  }

  static const char* value(const ::uav_mavros_simulation::target_local_pos&) { return value(); }
};


// service_traits::MD5Sum< ::uav_mavros_simulation::target_local_posRequest> should match
// service_traits::MD5Sum< ::uav_mavros_simulation::target_local_pos >
template<>
struct MD5Sum< ::uav_mavros_simulation::target_local_posRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_mavros_simulation::target_local_pos >::value();
  }
  static const char* value(const ::uav_mavros_simulation::target_local_posRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_mavros_simulation::target_local_posRequest> should match
// service_traits::DataType< ::uav_mavros_simulation::target_local_pos >
template<>
struct DataType< ::uav_mavros_simulation::target_local_posRequest>
{
  static const char* value()
  {
    return DataType< ::uav_mavros_simulation::target_local_pos >::value();
  }
  static const char* value(const ::uav_mavros_simulation::target_local_posRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_mavros_simulation::target_local_posResponse> should match
// service_traits::MD5Sum< ::uav_mavros_simulation::target_local_pos >
template<>
struct MD5Sum< ::uav_mavros_simulation::target_local_posResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_mavros_simulation::target_local_pos >::value();
  }
  static const char* value(const ::uav_mavros_simulation::target_local_posResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_mavros_simulation::target_local_posResponse> should match
// service_traits::DataType< ::uav_mavros_simulation::target_local_pos >
template<>
struct DataType< ::uav_mavros_simulation::target_local_posResponse>
{
  static const char* value()
  {
    return DataType< ::uav_mavros_simulation::target_local_pos >::value();
  }
  static const char* value(const ::uav_mavros_simulation::target_local_posResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_MAVROS_SIMULATION_MESSAGE_TARGET_LOCAL_POS_H
