// Generated by gencpp from file uav_mavros_simulation/target_global_posRequest.msg
// DO NOT EDIT!


#ifndef UAV_MAVROS_SIMULATION_MESSAGE_TARGET_GLOBAL_POSREQUEST_H
#define UAV_MAVROS_SIMULATION_MESSAGE_TARGET_GLOBAL_POSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mavros_msgs/GlobalPositionTarget.h>

namespace uav_mavros_simulation
{
template <class ContainerAllocator>
struct target_global_posRequest_
{
  typedef target_global_posRequest_<ContainerAllocator> Type;

  target_global_posRequest_()
    : goal_pos()  {
    }
  target_global_posRequest_(const ContainerAllocator& _alloc)
    : goal_pos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mavros_msgs::GlobalPositionTarget_<ContainerAllocator>  _goal_pos_type;
  _goal_pos_type goal_pos;





  typedef boost::shared_ptr< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> const> ConstPtr;

}; // struct target_global_posRequest_

typedef ::uav_mavros_simulation::target_global_posRequest_<std::allocator<void> > target_global_posRequest;

typedef boost::shared_ptr< ::uav_mavros_simulation::target_global_posRequest > target_global_posRequestPtr;
typedef boost::shared_ptr< ::uav_mavros_simulation::target_global_posRequest const> target_global_posRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator1> & lhs, const ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goal_pos == rhs.goal_pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator1> & lhs, const ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_mavros_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d9ece801327c4b84f63aa6e9a5c0c41";
  }

  static const char* value(const ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d9ece801327c4b8ULL;
  static const uint64_t static_value2 = 0x4f63aa6e9a5c0c41ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_mavros_simulation/target_global_posRequest";
  }

  static const char* value(const ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/GlobalPositionTarget goal_pos\n"
"\n"
"================================================================================\n"
"MSG: mavros_msgs/GlobalPositionTarget\n"
"# Message for SET_POSITION_TARGET_GLOBAL_INT\n"
"#\n"
"# https://mavlink.io/en/messages/common.html#SET_POSITION_TARGET_GLOBAL_INT\n"
"# Some complex system requires all feautures that mavlink\n"
"# message provide. See issue #402, #415.\n"
"\n"
"std_msgs/Header header\n"
"\n"
"uint8 coordinate_frame\n"
"uint8 FRAME_GLOBAL_INT = 5\n"
"uint8 FRAME_GLOBAL_REL_ALT = 6\n"
"uint8 FRAME_GLOBAL_TERRAIN_ALT = 11\n"
"\n"
"uint16 type_mask\n"
"uint16 IGNORE_LATITUDE = 1	# Position ignore flags\n"
"uint16 IGNORE_LONGITUDE = 2\n"
"uint16 IGNORE_ALTITUDE = 4\n"
"uint16 IGNORE_VX = 8	# Velocity vector ignore flags\n"
"uint16 IGNORE_VY = 16\n"
"uint16 IGNORE_VZ = 32\n"
"uint16 IGNORE_AFX = 64	# Acceleration/Force vector ignore flags\n"
"uint16 IGNORE_AFY = 128\n"
"uint16 IGNORE_AFZ = 256\n"
"uint16 FORCE = 512	# Force in af vector flag\n"
"uint16 IGNORE_YAW = 1024\n"
"uint16 IGNORE_YAW_RATE = 2048\n"
"\n"
"float64 latitude\n"
"float64 longitude\n"
"float32 altitude	# in meters, AMSL or above terrain\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 acceleration_or_force\n"
"float32 yaw\n"
"float32 yaw_rate\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct target_global_posRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_mavros_simulation::target_global_posRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal_pos: ";
    s << std::endl;
    Printer< ::mavros_msgs::GlobalPositionTarget_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MAVROS_SIMULATION_MESSAGE_TARGET_GLOBAL_POSREQUEST_H
