(cl:defpackage uav_mavros_simulation-srv
  (:use )
  (:export
   "GOTO_ARUCO"
   "<GOTO_ARUCO-REQUEST>"
   "GOTO_ARUCO-REQUEST"
   "<GOTO_ARUCO-RESPONSE>"
   "GOTO_ARUCO-RESPONSE"
   "LAND_ARUCO"
   "<LAND_ARUCO-REQUEST>"
   "LAND_ARUCO-REQUEST"
   "<LAND_ARUCO-RESPONSE>"
   "LAND_ARUCO-RESPONSE"
   "TARGET_GLOBAL_POS"
   "<TARGET_GLOBAL_POS-REQUEST>"
   "TARGET_GLOBAL_POS-REQUEST"
   "<TARGET_GLOBAL_POS-RESPONSE>"
   "TARGET_GLOBAL_POS-RESPONSE"
   "TARGET_LOCAL_POS"
   "<TARGET_LOCAL_POS-REQUEST>"
   "TARGET_LOCAL_POS-REQUEST"
   "<TARGET_LOCAL_POS-RESPONSE>"
   "TARGET_LOCAL_POS-RESPONSE"
  ))

