source /workspace/ros_ws/devel/setup.bash
source /opt/ros/melodic/setup.bash

export ROS_MASTER_URI=http://localhost:11311
export ROS_HOSTNAME=localhost

source /workspace/Firmware/Tools/setup_gazebo.bash /workspace/Firmware /workspace/Firmware/build/px4_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:/workspace/Firmware:/workspace/Firmware/Tools/sitl_gazebo

#export PX4_HOME_LAT=55.47197622
#export PX4_HOME_LON=10.32480953
#export PX4_HOME_ALT=7.4000000

# bash /workspace/install_geographiclib_datasets.sh

#alias seit-ws="source /workspace/ros_ws/devel/setup.bash && source /workspace/ros_ws/src/eit_playground/setup_gazebo.bash"
#alias peit-ws="cd /workspace/ros_ws && seit-ws"
#alias beit-ws="peit-ws && catkin build"
alias src="source devel/setup.bash"

alias killgazebo="pkill -9 gazebo & pkill -9 gzserver & pkill -9 gzclient & pkill -9 gazebo_gui"

export ROSCONSOLE_FORMAT='[${severity}] [${node}] [${time}]: ${message}'